### ISSUE TITLE
Charmap Error

### ISSUE THREAD

**Issue by Xyqc** [RELIHR/Discord-Status-Rotator#3]
`Traceback (most recent call last):
  File "C:\Users\ADMIN\Downloads\statuschanger\Discord-Status-Changer\main.py", line 70, in <module>
    emojis = read_statuses("emojis.txt")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ADMIN\Downloads\statuschanger\Discord-Status-Changer\main.py", line 46, in read_statuses
    return [line.strip() for line in file.readlines()]
                                     ^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 5: character maps to <undefined>`

How to fix?

**Comment by Xyqc** [comment]
This seems to have something to do UTF-8 Encoding.

**Comment by RELIHR** [comment]
It should let you now, there is the utf-8 encoding.
