### ISSUE TITLE
help me eerror

### ISSUE THREAD

**Issue by Tofek12222** [RELIHR/Discord-Status-Rotator#4]
Traceback (most recent call last):
  File "c:\Users\crsg2\Downloads\Discord-Status-Rotator-main\main.py", line 58, in <module>   
    config = load_config()
             ^^^^^^^^^^^^^
  File "c:\Users\crsg2\Downloads\Discord-Status-Rotator-main\main.py", line 50, in load_config
    with open("config.json", "r") as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'

**Comment by RELIHR** [comment]
It seems that you do not have the config.json file with the other files, you can create it and put the content there:

{
  "token": "discord-account-token",
  "status_sequence": ["online", "idle", "dnd"],
  "clear_enabled": true,
  "clear_interval": 15,
  "speed_rotator": 5
}
